leftnav:
- identifier: c649638c-8d02-4221-ba19-ebc202192803
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: c2b5e29a-28a5-4999-b4db-92e9fa59b798
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 20
- identifier: dc60f1da-e984-4045-b07c-af4129d934e0
  name: Lecture Notes and Readings
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: a5d954ee-e1c0-4ff2-a4da-7c2db12f9e49
  name: Lecture Videos
  pageRef: /video_galleries/lecture-videos
  weight: 40
- identifier: a7e73205-5887-4af2-b241-f0726443b1b0
  name: Problem Sets
  pageRef: /pages/problem-sets
  weight: 50
